export { DashboardPage } from "./DashboardPage";
export { TodayPage } from "./TodayPage";
export { TasksPage } from "./TasksPage";
export { NotesPage } from "./NotesPage";
export { RemindersPage } from "./RemindersPage";
export { CalendarPage } from "./CalendarPage";
export { SearchPage } from "./SearchPage";
export { SettingsPage } from "./SettingsPage";
export { HistoryPage } from "./HistoryPage";